// Generated from chinese_voices_35.json and full_chinese_voices.json
// swiftlint:disable all

enum VoiceCatalog {

    private static let chinese35IDs: Set<String> = [
        "wuu-CN-XiaotongNeural",
        "wuu-CN-YunzheNeural",
        "yue-CN-XiaoMinNeural",
        "yue-CN-YunSongNeural",
        "zh-CN-XiaochenNeural",
        "zh-CN-XiaohanNeural",
        "zh-CN-XiaomengNeural",
        "zh-CN-XiaomoNeural",
        "zh-CN-XiaoqiuNeural",
        "zh-CN-XiaorouNeural",
        "zh-CN-XiaoruiNeural",
        "zh-CN-XiaoshuangNeural",
        "zh-CN-XiaoxiaoNeural",
        "zh-CN-XiaoyanNeural",
        "zh-CN-XiaoyiNeural",
        "zh-CN-XiaoyouNeural",
        "zh-CN-XiaoyuNeural",
        "zh-CN-XiaozhenNeural",
        "zh-CN-YunfengNeural",
        "zh-CN-YunhaoNeural",
        "zh-CN-YunjianNeural",
        "zh-CN-YunjieNeural",
        "zh-CN-YunxiNeural",
        "zh-CN-YunxiaNeural",
        "zh-CN-YunyangNeural",
        "zh-CN-YunyeNeural",
        "zh-CN-YunzeNeural",
        "zh-CN-guangxi-YunqiNeural",
        "zh-CN-henan-YundengNeural",
        "zh-CN-liaoning-XiaobeiNeural",
        "zh-CN-liaoning-YunbiaoNeural",
        "zh-CN-shaanxi-XiaoniNeural",
        "zh-CN-shandong-YunxiangNeural",
        "zh-CN-sichuan-YunxiNeural",
        "zh-HK-HiuGaaiNeural",
        "zh-HK-HiuMaanNeural",
        "zh-HK-WanLungNeural",
        "zh-TW-HsiaoChenNeural",
        "zh-TW-HsiaoYuNeural",
        "zh-TW-YunJheNeural"
    ]

    /// 常用经典音色 (过滤自 fullChinese，共 40 个)
    static var chinese35: [VoiceItem] { fullChinese.filter { chinese35IDs.contains($0.id) } }

    /// 全音色模式 (76 个，含 Dragon HD / MAI-Voice-2 等)
    static let fullChinese: [VoiceItem] = [
        VoiceItem(id: "wuu-CN-XiaotongNeural", name: "晓彤", locale: "wuu-CN", gender: .female, styleList: nil),
        VoiceItem(id: "wuu-CN-YunzheNeural", name: "云哲", locale: "wuu-CN", gender: .male, styleList: nil),
        VoiceItem(id: "yue-CN-XiaoMinNeural", name: "晓敏", locale: "yue-CN", gender: .female, styleList: nil),
        VoiceItem(id: "yue-CN-YunSongNeural", name: "云松", locale: "yue-CN", gender: .male, styleList: nil),
        VoiceItem(id: "zh-CN-Ivoryserenade:DragonHDOmniLatestNeural", name: "象牙白 龙HD全能版", locale: "zh-CN", gender: .female, styleList: nil),
        VoiceItem(id: "zh-CN-Xiaoshuang:DragonHDOmniLatestNeural", name: "晓双 龙HD全能版", locale: "zh-CN", gender: .female, styleList: nil),
        VoiceItem(id: "zh-CN-Xiaoxiao:DragonHDFlashLatestNeural", name: "晓晓 龙HD闪速版", locale: "zh-CN", gender: .female, styleList: ["angry", "chat", "cheerful", "customer-service", "excited", "fearful", "sad", "voice-assistant", "comforting", "debating", "disappointed", "shy", "sorry", "strict", "whispering"]),
        VoiceItem(id: "zh-CN-Xiaoxiao2:DragonHDFlashLatestNeural", name: "晓晓2 龙HD闪速版", locale: "zh-CN", gender: .female, styleList: ["affectionate", "angry", "anxious", "cheerful", "curious", "disappointed", "empathetic", "encouraging", "excited", "fearful", "guilty", "lonely", "poetry-reading", "sad", "surprised", "sentimental", "sorry", "story-telling", "whispering", "tired"]),
        VoiceItem(id: "zh-CN-Xiaochen:DragonHDLatestNeural", name: "晓辰 龙HD版", locale: "zh-CN", gender: .female, styleList: nil),
        VoiceItem(id: "zh-CN-Yunxiao:DragonHDFlashLatestNeural", name: "云晓 龙HD闪速版", locale: "zh-CN", gender: .male, styleList: nil),
        VoiceItem(id: "zh-CN-Yunyi:DragonHDFlashLatestNeural", name: "云逸 龙HD闪速版", locale: "zh-CN", gender: .male, styleList: ["assassin", "captain", "cavalier", "prince", "game-narrator", "geomancer", "poet"]),
        VoiceItem(id: "zh-CN-Yunfan:DragonHDLatestNeural", name: "云帆 龙HD版", locale: "zh-CN", gender: .male, styleList: nil),
        VoiceItem(id: "zh-CN-Xiaoyue:DragonHDOmniLatestNeural", name: "晓月 龙HD全能版", locale: "zh-CN", gender: .female, styleList: nil),
        VoiceItem(id: "zh-CN-Yunqi:DragonHDOmniLatestNeural", name: "云奇 龙HD全能版", locale: "zh-CN", gender: .male, styleList: nil),
        VoiceItem(id: "zh-CN-Maroonallegro:DragonHDOmniLatestNeural", name: "栗红 龙HD全能版", locale: "zh-CN", gender: .female, styleList: nil),
        VoiceItem(id: "zh-CN-Peachgranite:DragonHDOmniLatestNeural", name: "桃黄 龙HD全能版", locale: "zh-CN", gender: .female, styleList: nil),
        VoiceItem(id: "zh-CN-XiaoxiaoNeural", name: "晓晓", locale: "zh-CN", gender: .female, styleList: ["assistant", "chat", "customerservice", "newscast", "affectionate", "angry", "calm", "cheerful", "disgruntled", "fearful", "gentle", "lyrical", "sad", "serious", "poetry-reading", "friendly", "chat-casual", "whispering", "sorry", "excited"]),
        VoiceItem(id: "zh-CN-YunxiNeural", name: "云希", locale: "zh-CN", gender: .male, styleList: ["narration-relaxed", "embarrassed", "fearful", "cheerful", "disgruntled", "serious", "angry", "sad", "depressed", "chat", "assistant", "newscast"]),
        VoiceItem(id: "zh-CN-YunjianNeural", name: "云健", locale: "zh-CN", gender: .male, styleList: ["narration-relaxed", "sports-commentary", "sports-commentary-excited", "angry", "disgruntled", "cheerful", "sad", "serious", "depressed", "documentary-narration"]),
        VoiceItem(id: "zh-CN-XiaoyiNeural", name: "晓伊", locale: "zh-CN", gender: .female, styleList: ["angry", "disgruntled", "affectionate", "cheerful", "fearful", "sad", "embarrassed", "serious", "gentle"]),
        VoiceItem(id: "zh-CN-YunyangNeural", name: "云扬", locale: "zh-CN", gender: .male, styleList: ["customerservice", "narration-professional", "newscast-casual"]),
        VoiceItem(id: "zh-CN-XiaochenNeural", name: "晓辰", locale: "zh-CN", gender: .female, styleList: ["livecommercial"]),
        VoiceItem(id: "zh-CN-Lingqing:DragonHDFlashLatestNeural", name: "灵清 龙HD闪速版", locale: "zh-CN", gender: .female, styleList: nil),
        VoiceItem(id: "zh-CN-Xiaochen:DragonHDFlashLatestNeural", name: "晓辰 龙HD闪速版", locale: "zh-CN", gender: .female, styleList: ["cheerful", "debating", "empathetic", "live-commercial", "poetry-reading", "sad", "sorry"]),
        VoiceItem(id: "zh-CN-XiaochenMultilingualNeural", name: "晓辰 多语言", locale: "zh-CN", gender: .female, styleList: nil),
        VoiceItem(id: "zh-CN-Xiaohan:DragonHDFlashLatestNeural", name: "晓涵 龙HD闪速版", locale: "zh-CN", gender: .female, styleList: ["affectionate", "angry", "cheerful", "complaining", "fearful", "gentle", "sad", "shy", "strict"]),
        VoiceItem(id: "zh-CN-XiaohanNeural", name: "晓涵", locale: "zh-CN", gender: .female, styleList: ["calm", "fearful", "cheerful", "disgruntled", "serious", "angry", "sad", "gentle", "affectionate", "embarrassed"]),
        VoiceItem(id: "zh-CN-XiaomengNeural", name: "晓梦", locale: "zh-CN", gender: .female, styleList: ["chat"]),
        VoiceItem(id: "zh-CN-XiaomoNeural", name: "晓墨", locale: "zh-CN", gender: .female, styleList: ["embarrassed", "calm", "fearful", "cheerful", "disgruntled", "serious", "angry", "sad", "depressed", "affectionate", "gentle", "envious"]),
        VoiceItem(id: "zh-CN-XiaoqiuNeural", name: "晓秋", locale: "zh-CN", gender: .female, styleList: nil),
        VoiceItem(id: "zh-CN-XiaorouNeural", name: "晓柔", locale: "zh-CN", gender: .female, styleList: nil),
        VoiceItem(id: "zh-CN-XiaoruiNeural", name: "晓睿", locale: "zh-CN", gender: .female, styleList: ["calm", "fearful", "angry", "sad"]),
        VoiceItem(id: "zh-CN-Xiaoshuang:DragonHDFlashLatestNeural", name: "晓双 龙HD闪速版", locale: "zh-CN", gender: .female, styleList: ["chat"]),
        VoiceItem(id: "zh-CN-XiaoshuangMultilingualNeural", name: "晓双 多语言", locale: "zh-CN", gender: .female, styleList: ["chat"]),
        VoiceItem(id: "zh-CN-XiaoshuangNeural", name: "晓双", locale: "zh-CN", gender: .female, styleList: ["chat"]),
        VoiceItem(id: "zh-CN-XiaoxiaoDialectsNeural", name: "晓晓 方言", locale: "zh-CN", gender: .female, styleList: nil),
        VoiceItem(id: "zh-CN-XiaoxiaoMultilingualNeural", name: "晓晓 多语言", locale: "zh-CN", gender: .female, styleList: ["affectionate", "cheerful", "empathetic", "excited", "poetry-reading", "sorry", "story"]),
        VoiceItem(id: "zh-CN-XiaoyanNeural", name: "晓颜", locale: "zh-CN", gender: .female, styleList: nil),
        VoiceItem(id: "zh-CN-Xiaoyi:DragonHDFlashLatestNeural", name: "晓伊 龙HD闪速版", locale: "zh-CN", gender: .female, styleList: ["angry", "cheerful", "complaining", "cute", "gentle", "nervous", "sad", "shy", "strict"]),
        VoiceItem(id: "zh-CN-Xiaoyou:DragonHDFlashLatestNeural", name: "晓悠 龙HD闪速版", locale: "zh-CN", gender: .female, styleList: ["chat", "angry", "cheerful", "poetry-reading", "sad", "story-telling", "cute"]),
        VoiceItem(id: "zh-CN-XiaoyouMultilingualNeural", name: "晓悠 多语言", locale: "zh-CN", gender: .female, styleList: ["chat", "angry", "cheerful", "poetry-reading", "sad", "story", "cute"]),
        VoiceItem(id: "zh-CN-XiaoyouNeural", name: "晓悠", locale: "zh-CN", gender: .female, styleList: nil),
        VoiceItem(id: "zh-CN-Xiaoyu:DragonHDFlashLatestNeural", name: "晓宇 龙HD闪速版", locale: "zh-CN", gender: .female, styleList: ["debating", "angry", "cheerful", "comforting", "sad", "sorry"]),
        VoiceItem(id: "zh-CN-XiaoyuMultilingualNeural", name: "晓宇 多语言", locale: "zh-CN", gender: .female, styleList: nil),
        VoiceItem(id: "zh-CN-XiaoyuNeural", name: "晓宇", locale: "zh-CN", gender: .female, styleList: nil),
        VoiceItem(id: "zh-CN-XiaozhenNeural", name: "晓甄", locale: "zh-CN", gender: .female, styleList: ["angry", "disgruntled", "cheerful", "fearful", "sad", "serious"]),
        VoiceItem(id: "zh-CN-YunfanMultilingualNeural", name: "云帆 多语言", locale: "zh-CN", gender: .male, styleList: nil),
        VoiceItem(id: "zh-CN-YunfengNeural", name: "云枫", locale: "zh-CN", gender: .male, styleList: ["angry", "disgruntled", "cheerful", "fearful", "sad", "serious", "depressed"]),
        VoiceItem(id: "zh-CN-Yunhan:DragonHDFlashLatestNeural", name: "云瀚 龙HD闪速版", locale: "zh-CN", gender: .male, styleList: ["angry", "cheerful", "curious", "empathetic", "encouraging", "excited", "guilty", "lonely", "sad", "serious", "sorry", "whispering", "surprised", "tired"]),
        VoiceItem(id: "zh-CN-YunhaoNeural", name: "云皓", locale: "zh-CN", gender: .male, styleList: ["advertisement-upbeat"]),
        VoiceItem(id: "zh-CN-YunjieNeural", name: "云杰", locale: "zh-CN", gender: .male, styleList: nil),
        VoiceItem(id: "zh-CN-Yunxi:DragonHDFlashLatestNeural", name: "云希 龙HD闪速版", locale: "zh-CN", gender: .male, styleList: ["angry", "chat", "cheerful", "complaining", "depressed", "fearful", "news", "sad", "shy", "strict", "voice-assistant"]),
        VoiceItem(id: "zh-CN-Yunxia:DragonHDFlashLatestNeural", name: "云夏 龙HD闪速版", locale: "zh-CN", gender: .male, styleList: ["affectionate", "angry", "comforting", "cheerful", "encouraging", "excited", "fearful", "sad", "surprised"]),
        VoiceItem(id: "zh-CN-YunxiaNeural", name: "云夏", locale: "zh-CN", gender: .male, styleList: ["calm", "fearful", "cheerful", "angry", "sad"]),
        VoiceItem(id: "zh-CN-YunxiaoMultilingualNeural", name: "云晓 多语言", locale: "zh-CN", gender: .male, styleList: nil),
        VoiceItem(id: "zh-CN-Yunye:DragonHDFlashLatestNeural", name: "云野 龙HD闪速版", locale: "zh-CN", gender: .male, styleList: nil),
        VoiceItem(id: "zh-CN-YunyeNeural", name: "云野", locale: "zh-CN", gender: .male, styleList: ["embarrassed", "calm", "fearful", "cheerful", "disgruntled", "serious", "angry", "sad"]),
        VoiceItem(id: "zh-CN-YunyiMultilingualNeural", name: "云逸 多语言", locale: "zh-CN", gender: .male, styleList: nil),
        VoiceItem(id: "zh-CN-YunzeNeural", name: "云泽", locale: "zh-CN", gender: .male, styleList: ["calm", "fearful", "cheerful", "disgruntled", "serious", "angry", "sad", "depressed", "documentary-narration"]),
        VoiceItem(id: "zh-CN-Bo:MAI-Voice-2", name: "波 MAI音2", locale: "zh-CN", gender: .male, styleList: ["angry", "confused", "determined", "disgusted", "embarrassed", "excited", "fearful", "happy", "hopeful", "jealous", "joyful", "regretful", "relieved", "sad", "shouting", "softvoice", "surprised", "whispering"]),
        VoiceItem(id: "zh-CN-Lan:MAI-Voice-2", name: "岚 MAI音2", locale: "zh-CN", gender: .female, styleList: ["angry", "confused", "disgusted", "embarrassed", "excited", "fearful", "happy", "joyful", "sad", "surprised"]),
        VoiceItem(id: "zh-CN-Mei:MAI-Voice-2", name: "梅 MAI音2", locale: "zh-CN", gender: .female, styleList: ["angry", "confused", "determined", "disgusted", "embarrassed", "excited", "fearful", "happy", "hopeful", "jealous", "joyful", "regretful", "relieved", "sad", "shouting", "softvoice", "surprised", "whispering"]),
        VoiceItem(id: "zh-CN-Wei:MAI-Voice-2", name: "威 MAI音2", locale: "zh-CN", gender: .male, styleList: ["angry", "confused", "disgusted", "embarrassed", "excited", "fearful", "happy", "hopeful", "jealous", "joyful", "regretful", "sad", "surprised"]),
        VoiceItem(id: "zh-CN-guangxi-YunqiNeural", name: "云奇 广西", locale: "zh-CN-guangxi", gender: .male, styleList: nil),
        VoiceItem(id: "zh-CN-henan-YundengNeural", name: "云登", locale: "zh-CN-henan", gender: .male, styleList: nil),
        VoiceItem(id: "zh-CN-liaoning-XiaobeiNeural", name: "晓北 辽宁", locale: "zh-CN-liaoning", gender: .female, styleList: nil),
        VoiceItem(id: "zh-CN-liaoning-YunbiaoNeural", name: "云彪 辽宁", locale: "zh-CN-liaoning", gender: .male, styleList: nil),
        VoiceItem(id: "zh-CN-shaanxi-XiaoniNeural", name: "晓妮", locale: "zh-CN-shaanxi", gender: .female, styleList: nil),
        VoiceItem(id: "zh-CN-shandong-YunxiangNeural", name: "云翔", locale: "zh-CN-shandong", gender: .male, styleList: nil),
        VoiceItem(id: "zh-CN-sichuan-YunxiNeural", name: "云希 四川", locale: "zh-CN-sichuan", gender: .male, styleList: nil),
        VoiceItem(id: "zh-HK-HiuMaanNeural", name: "曉曼", locale: "zh-HK", gender: .female, styleList: nil),
        VoiceItem(id: "zh-HK-WanLungNeural", name: "雲龍", locale: "zh-HK", gender: .male, styleList: nil),
        VoiceItem(id: "zh-HK-HiuGaaiNeural", name: "曉佳", locale: "zh-HK", gender: .female, styleList: nil),
        VoiceItem(id: "zh-TW-HsiaoChenNeural", name: "曉臻", locale: "zh-TW", gender: .female, styleList: nil),
        VoiceItem(id: "zh-TW-YunJheNeural", name: "雲哲", locale: "zh-TW", gender: .male, styleList: nil),
        VoiceItem(id: "zh-TW-HsiaoYuNeural", name: "曉雨", locale: "zh-TW", gender: .female, styleList: nil),
    ]

}